export enum MultiStepFormActionTypes {
    SET_STEP_ONE = "SET_STEP_ONE",
    SET_STEP_TWO = "SET_STEP_TWO",
    SET_STEP_THREE = "SET_STEP_THREE",
    SET_STEP_FOUR = "SET_STEP_FOUR",
    SET_STEP_FIVE = "SET_STEP_FIVE",
    LOAD_NEXT_STEP = "LOAD_NEXT_STEP",
    LOAD_PREV_STEP = "LOAD_PREV_STEP",
    RESET = "RESET",
}
